### ISSUE TITLE
Tax calculation

### ISSUE THREAD

**Issue by PaulEFarr** [GoldbergAlexander/habitat4humanity#3]
This one's pretty simple.  Tax calculation should be truncated after the second decimal place.

**Comment by PaulEFarr** [comment]
Looks like we quantum weirdness elsewhere in the system.
![screen shot 2018-07-02 at 12 04 54 pm](https://user-images.githubusercontent.com/40703259/42174438-57e0c3f6-7df0-11e8-93e1-f05fbfb754bf.png)

**Comment by GoldbergAlexander** [comment]
Tax calculation is now rounded to two decimal points on calculations. In addition, all processed values are rounded as well.
